export const initialItems = [
  {
    id: 0,
    title: "Освітлення",
    img: "lamp.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "light",
    price: "399.99",
  },
  {
    id: 1,
    title: "Стілець сірий",
    img: "chair-grey.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "chairs",
    price: "599.99",
  },
  {
    id: 2,
    title: "Стіл",
    img: "table.webp",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "tables",
    price: "999.99",
  },
  {
    id: 3,
    title: "Канапа",
    img: "sofa.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "sofa",
    price: "1699.99",
  },
  {
    id: 4,
    title: "Лампа",
    img: "wall-light.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "light",
    price: "499.99",
  },
  {
    id: 5,
    title: "Стілець білий",
    img: "chair-white.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "chairs",
    price: "299.99",
  },
];
